"""description of change

Revision ID: 6d189d551ead
Revises: e8132f513d1b
Create Date: 2026-06-19 14:37:52.551774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d189d551ead'
down_revision: Union[str, Sequence[str], None] = 'e8132f513d1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_platform_source'), 'posts', type_='unique')
    op.create_unique_constraint('uq_platform_external', 'posts', ['platform_id', 'external_id'])
    op.alter_column('results', 'control_conversions',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('results', 'treatment_conversions',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('results', 'control_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('results', 'treatment_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('results', 'lift',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('results', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('results', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('results', 'lift',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('results', 'treatment_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('results', 'control_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('results', 'treatment_conversions',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('results', 'control_conversions',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('uq_platform_external', 'posts', type_='unique')
    op.create_unique_constraint(op.f('uq_platform_source'), 'posts', ['platform_id', 'external_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
