"""add engagement columns to posts

Revision ID: 724d83b2693a
Revises: 
Create Date: 2026-06-07 22:59:23.910970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '724d83b2693a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('posts', sa.Column('view_count', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('like_count', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('comment_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'comment_count')
    op.drop_column('posts', 'like_count')
    op.drop_column('posts', 'view_count')
    # ### end Alembic commands ###
