"""add post and alert indexes

Revision ID: e3549481afb7
Revises: 6d189d551ead
Create Date: 2026-06-21 22:45:04.469591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3549481afb7'
down_revision: Union[str, Sequence[str], None] = '6d189d551ead'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_alerts_project_triggered', 'alerts', ['project_id', sa.literal_column('triggered_at DESC')], unique=False)
    op.create_index('ix_posts_topic_id', 'posts', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_topic_id', table_name='posts')
    op.drop_index('ix_alerts_project_triggered', table_name='alerts')
    # ### end Alembic commands ###
