"""adding is_active flag for topics

Revision ID: ff5d0811749e
Revises: 83182d75c0cb
Create Date: 2026-06-10 22:42:01.872232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff5d0811749e'
down_revision: Union[str, Sequence[str], None] = '83182d75c0cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'is_active')
    # ### end Alembic commands ###
